name: Gatsby Publish

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false

      - name: remove non-site source files
        run: |
          find . -mindepth 1  -maxdepth 1 ! -name .git ! -name domain-groupie -exec rm -rf {} \;

      - name: build site from sources
        run: |
          cd domain-groupie
          npm install
          npm run-script build

      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          persist-credentials: true
          path: temp          

      - name: replace site sources with generated site
        run: |
          find temp/ -mindepth 1  -maxdepth 1 ! -name .git -exec rm -rvf {} \;
          mv domain-groupie/public/* temp/
          echo ____
          find temp/ -maxdepth 1

      - name: push gh-pages branch
        run: |
          cd temp/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --amend -m "Generated $(date) from $GITHUB_SHA"
          git push --force origin gh-pages


#      - name: move files # move the public built files into root dir and remove others.
#        if: ${{ success() }}
#        run: |
#          mv -v temp/domain-groupie/public/* ./
#          rm -rf temp          

