name: Gatsby Publish

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false

      - name: remove non-site related files
        run: |
          find . -maxdepth 1 ! -name .git ! -name domain-groupie -exec rm -rf {} \;

      - name: build site
        run: |
          cd domain-groupie
          npm install
          npm run-script build

      - name: site to root
        run: |
          mv domain-groupie/public/* .
          find . -maxdepth 1
          rm -rf domain-groupie/


#      - name: move files # move the public built files into root dir and remove others.
#        if: ${{ success() }}
#        run: |
#          mv -v temp/domain-groupie/public/* ./
#          rm -rf temp          

