name: Gatsby Publish

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master  branch 
        uses: actions/checkout@v2
        with:
          ref: master
          path: temp
          persist-credentials: false

#      - name: remove all files # remove files.
#        run: |
#          rm -rvf *

      - name: run install and build
        run: |
          cd temp/domain-groupie
          npm install
          npm run-script build

      - name: move files # move the public built files into root dir and remove others.
        if: ${{ success() }}
        run: |
          mv -v temp/domain-groupie/public/* ./
          rm -rvf temp          

